#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=ass2_1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:29:30
#SBATCH --output=/home/scur1399/uvadlc_practicals_2023/assignment2/part2/part2_1_output_%A.out
#SBATCH --error=/home/scur1399/uvadlc_practicals_2023/assignment2/part1/part2_1_file_name_%A.out

# Your job starts in the directory where you call sbatch
module purge
module load 2022
module load Anaconda3/2022.05

source activate dl2023
cd /home/scur1399/uvadlc_practicals_2023/assignment2/part2
# Run your code
srun python -u /home/scur1399/uvadlc_practicals_2023/assignment2/part2/clipzs.py