#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=ass1_1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=part1_output_%A.out
#SBATCH --error=part1_file_name_%A.out

# Your job starts in the directory where you call sbatch
cd /home/scur1399/uvadlc_practicals_2023/assignment2/part2
# Activate your environment
source activate dl2023
# Run your code
srun python -u train.py